# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dfb6a2f06a48e290d16ee687d405e904"
name = "b2bquote-new"
handle = "b2bquote-new"
application_url = "https://interference-saw-gps-danny.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://interference-saw-gps-danny.trycloudflare.com/auth/callback", "https://interference-saw-gps-danny.trycloudflare.com/auth/shopify/callback", "https://interference-saw-gps-danny.trycloudflare.com/api/auth/callback"]


[app_proxy]
url = "https://interference-saw-gps-danny.trycloudflare.com/api/proxy"
subpath = "b2bquote-new"
prefix = "apps"

[pos]
embedded = false
